// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ9ucv8w3Opm223CxFw_hF7PsgEuO-Uu8',
    appId: '1:744898986170:web:376fc64653017e44524283',
    messagingSenderId: '744898986170',
    projectId: 'software-engineering-jis',
    authDomain: 'software-engineering-jis.firebaseapp.com',
    storageBucket: 'software-engineering-jis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjw78RlbUhkzspRyLEmt9lVwSRQRCGbIA',
    appId: '1:744898986170:android:3fe39faed7834594524283',
    messagingSenderId: '744898986170',
    projectId: 'software-engineering-jis',
    storageBucket: 'software-engineering-jis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzuRMGBdgKZxSj74ygcJT7KhIh_vVgXdE',
    appId: '1:744898986170:ios:53d43e29d166750f524283',
    messagingSenderId: '744898986170',
    projectId: 'software-engineering-jis',
    storageBucket: 'software-engineering-jis.appspot.com',
    iosClientId: '744898986170-g26n2oiku7sv56f5jg4l7064cjmanbl4.apps.googleusercontent.com',
    iosBundleId: 'com.anirudh-cr2.jiss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzuRMGBdgKZxSj74ygcJT7KhIh_vVgXdE',
    appId: '1:744898986170:ios:53d43e29d166750f524283',
    messagingSenderId: '744898986170',
    projectId: 'software-engineering-jis',
    storageBucket: 'software-engineering-jis.appspot.com',
    iosClientId: '744898986170-g26n2oiku7sv56f5jg4l7064cjmanbl4.apps.googleusercontent.com',
    iosBundleId: 'com.anirudh-cr2.jiss',
  );
}
